name: Shopify Lighthouse CI

on:
  push:
    branches:
      - main

jobs:
  lighthouse-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Shopify Lighthouse CI
      run: npm install -g @shopify/lighthouse-ci

    - name: Run Shopify Lighthouse CI
      run: |
        lighthouse-ci $SHOP_STORE
      env:
        SHOP_STORE: ${{ secrets.SHOP_STORE }}
        SHOP_ACCESS_TOKEN: ${{ secrets.SHOP_ACCESS_TOKEN }}
