name: Run Lighthouse CI

on:
  push:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Lighthouse CI
        uses: lighthouse-ci-action@v1
        with:
          INPUT_STORE: ${{ secrets.SHOP_STORE }}
          INPUT_PASSWORD: ${{ secrets.SHOP_PASSWORD }}
          INPUT_PRODUCT_HANDLE: ${{ secrets.SHOP_PRODUCT_HANDLE }}
          INPUT_COLLECTION_HANDLE: ${{ secrets.SHOP_COLLECTION_HANDLE }}
          INPUT_THEME_ROOT: ${{ secrets.THEME_ROOT }}
          INPUT_PULL_THEME: ${{ secrets.SHOP_PULL_THEME }}
          INPUT_ACCESS_TOKEN: ${{ secrets.SHOP_ACCESS_TOKEN }}
          INPUT_APP_ID: ${{ secrets.SHOP_APP_ID }}
          INPUT_APP_PASSWORD: ${{ secrets.SHOP_APP_PASSWORD }}
          INPUT_LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          INPUT_LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_TOKEN }}
          INPUT_LHCI_MIN_SCORE_PERFORMANCE: ${{ secrets.LHCI_MIN_SCORE_PERFORMANCE }}
          INPUT_LHCI_MIN_SCORE_ACCESSIBILITY: ${{ secrets.LHCI_MIN_SCORE_ACCESSIBILITY }}
